#!/usr/bin/env bash

# exit on error
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "$BASEDIR"

if [[ ! -d ./dotbot ]] || git --work-tree="${DOTBOT_DIR}" --git-dir="${DOTBOT_DIR}/.git" diff-index --quiet HEAD -- ; then
  git submodule update --init --recursive "${DOTBOT_DIR}"
  git --work-tree="${DOTBOT_DIR}" --git-dir="${DOTBOT_DIR}/.git" submodule sync --recursive
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
