#!/usr/bin/env bash

# exit on error
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
ZINIT_DIR="zinit"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

pushd "$BASEDIR"

git submodule sync --recursive

if [[ ! -d ./${DOTBOT_DIR} ]] || git --work-tree="${DOTBOT_DIR}" --git-dir="${DOTBOT_DIR}/.git" diff-index --quiet HEAD -- ; then
  git submodule update --init --recursive "${DOTBOT_DIR}"
fi

if [[ ! -d ./${ZINIT_DIR} ]] || git --work-tree="${ZINIT_DIR}" --git-dir="${ZINIT_DIR}/.git" diff-index --quiet HEAD -- ; then
  git submodule update --init --recursive "${ZINIT_DIR}"
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
